git-pr: exit with status 1 on bad options

diff --git a/bin/git-pr b/bin/git-pr
--- a/bin/git-pr
+++ b/bin/git-pr
@@ -17,7 +17,7 @@ do
 	case $opt in
 	o) open=1;;
 	u) update=1;;
-	?) echo "Error: unknown option '-$OPTARG'" && exit;;
+	?) echo "Error: unknown option '-$OPTARG'" && exit 1;;
 	esac
 done
 shift $(($OPTIND - 1))
